# Generated by Django 4.2.7 on 2024-03-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0003_cargo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Автор"
                    ),
                ),
                (
                    "quote",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цитата",
                "verbose_name_plural": "Цитаты",
            },
        ),
    ]
