# Generated by Django 4.2.7 on 2024-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="Наименование типа хранения",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Описание"
                    ),
                ),
                ("storage_value", models.FloatField(verbose_name="Вместимость")),
                (
                    "warehouse",
                    models.ManyToManyField(
                        to="warehouses.warehouse", verbose_name="Склад"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип хранения",
                "verbose_name_plural": "Типы хранения",
            },
        ),
    ]
